name: weather_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  provider: ^6.1.5+1
  get_it: ^9.2.1
  shared_preferences: ^2.5.5
  internet_connection_checker: ^3.0.1
  dio: ^5.10.0
  cached_network_image: ^3.4.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/Group 3 (2).png
  android_12:
    image: assets/splashl.png
    icon_background_color: "#FFFFFF"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Group 3 (2).png"
  color: "#FFFFFF"
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Light.ttf
          weight: 300
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Bold.ttf
          weight: 700

